[project]
name = "uv-torch-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "numpy==1.26.3",
    "torch==2.3.1+cu121",
    "torchaudio==2.3.1+cu121",
    "torchvision==0.18.1+cu121",
]

[tool.uv]
extra-index-url = ["https://download.pytorch.org/whl/cu121"]
